#using official maven image
FROM maven 

#copying SpringMVCXML into container
COPY Java_Sample_App/SpringMVCSecurityXML /java_app/SpringMVCSecurityXML

# Set the Work directory
WORKDIR /java_app/SpringMVCSecurityXML

# buuild the application
RUN mvn clean install 

#using official tomcat:8 image
FROM tomcat:8

#copy the application in tomcat server
COPY --from=0 /java_app/SpringMVCSecurityXML/target/SpringMVCSecurityXML.war /usr/local/tomcat/webapps

# run the application
RUN echo "Deployment successful in TOMCAT"

#using official nginx image
FROM nginx

#remove the default configuration settings 
RUN rm -rf etc/nginx/conf.d/default.conf

#add the new configuration file
COPY ./tomcat-nginx.conf etc/nginx/conf.d/tomcat-nginx.conf

#test and reload new configuration 
RUN nginx -t 

#comment display
RUN echo "Deployment successful in NGINX"
